<template>
  <header>
    <HomeNavbar />
    <HomeDrawer />
    <div class="bg-white p-8">
      <div class="flex flex-col md:flex-row items-stretch gap-x-16 gap-y-8 max-w-6xl mx-auto">
        <div class="flex flex-col order-2 md:order-1 gap-3 justify-center items-center md:items-start flex-grow">
          <h1
            class="text-4xl md:text-5xl font-bold text-transparent text-center md:text-start bg-gradient-to-r from-teal-500 to-teal-400 bg-clip-text">
            Actions Vue</h1>
          <p class="text-lg text-center text-gray-600 md:text-start">Lorem ipsum dolor sit amet consectetur adipisicing
            elit. Magni eveniet quo repellendus. Nisi quos voluptas maxime ab doloremque nam officiis qui aspernatur
            eius soluta natus quae, reprehenderit aperiam, praesentium unde.</p>
          <button class="mt-4 bg-teal-600 hover:bg-teal-500 active:bg-teal-700 text-white px-4 py-2.5 rounded-full transition-all">Manage your
            notes</button>
        </div>
        <img class="w-10/12 mx-auto md:h-80 md:w-auto drop-shadow-lg order-1 md:order-2" src="/images/i_images.svg"
          alt="logo">
      </div>

    </div>
  </header>
  <main class="max-w-6xl mx-auto">
      <h3 id="preview" class="text-center text-3xl font-bold text-gray-600 my-4">Preview</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur nesciunt quos quisquam quam dignissimos, tempore corrupti non fugiat neque eligendi aliquid et deleniti quia exercitationem. Molestiae fuga doloremque ea eius? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore soluta, magnam hic nihil officia iste laborum iusto earum consequuntur! Distinctio, exercitationem. Eum ipsum iste quaerat quos at a rerum atque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum voluptate reiciendis mollitia, eum doloremque amet nulla voluptatum consequuntur. Deleniti ratione tenetur similique atque libero. Quo libero vitae animi quos exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, possimus magni vero dolore explicabo eaque. Maxime voluptatum animi aliquam quaerat, beatae esse numquam pariatur doloribus, deserunt totam natus rerum obcaecati. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, ipsum provident. Error quis facere pariatur ipsam, optio maxime commodi? Cumque dolores eaque, nobis magni nesciunt hic voluptatibus rem deleniti debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam accusamus laboriosam ipsa, ratione dicta delectus quam nisi culpa facilis cupiditate, inventore, aliquam perspiciatis facere? Quae perspiciatis veritatis eos voluptatibus? Sunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt fuga deleniti eos quisquam quis porro quaerat, at qui et! Assumenda doloribus reiciendis fugiat eos laboriosam eveniet placeat dicta blanditiis accusamus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos distinctio alias obcaecati eius provident quos nobis voluptas repellendus! Necessitatibus maiores sapiente laborum numquam cumque, eos vero totam ex rem cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias vero blanditiis doloribus natus ex, explicabo quasi excepturi tempora. Quaerat corrupti esse repudiandae iusto illo optio at voluptatibus, accusamus dolore minus.</p>
    
      <h3 id="features" class="text-center text-3xl font-bold text-gray-600 my-4">Preview</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur nesciunt quos quisquam quam dignissimos, tempore corrupti non fugiat neque eligendi aliquid et deleniti quia exercitationem. Molestiae fuga doloremque ea eius? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore soluta, magnam hic nihil officia iste laborum iusto earum consequuntur! Distinctio, exercitationem. Eum ipsum iste quaerat quos at a rerum atque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum voluptate reiciendis mollitia, eum doloremque amet nulla voluptatum consequuntur. Deleniti ratione tenetur similique atque libero. Quo libero vitae animi quos exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, possimus magni vero dolore explicabo eaque. Maxime voluptatum animi aliquam quaerat, beatae esse numquam pariatur doloribus, deserunt totam natus rerum obcaecati. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, ipsum provident. Error quis facere pariatur ipsam, optio maxime commodi? Cumque dolores eaque, nobis magni nesciunt hic voluptatibus rem deleniti debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam accusamus laboriosam ipsa, ratione dicta delectus quam nisi culpa facilis cupiditate, inventore, aliquam perspiciatis facere? Quae perspiciatis veritatis eos voluptatibus? Sunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt fuga deleniti eos quisquam quis porro quaerat, at qui et! Assumenda doloribus reiciendis fugiat eos laboriosam eveniet placeat dicta blanditiis accusamus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos distinctio alias obcaecati eius provident quos nobis voluptas repellendus! Necessitatibus maiores sapiente laborum numquam cumque, eos vero totam ex rem cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias vero blanditiis doloribus natus ex, explicabo quasi excepturi tempora. Quaerat corrupti esse repudiandae iusto illo optio at voluptatibus, accusamus dolore minus.</p>
    
      <h3 id="about" class="text-center text-3xl font-bold text-gray-600 my-4">Preview</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur nesciunt quos quisquam quam dignissimos, tempore corrupti non fugiat neque eligendi aliquid et deleniti quia exercitationem. Molestiae fuga doloremque ea eius? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore soluta, magnam hic nihil officia iste laborum iusto earum consequuntur! Distinctio, exercitationem. Eum ipsum iste quaerat quos at a rerum atque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum voluptate reiciendis mollitia, eum doloremque amet nulla voluptatum consequuntur. Deleniti ratione tenetur similique atque libero. Quo libero vitae animi quos exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, possimus magni vero dolore explicabo eaque. Maxime voluptatum animi aliquam quaerat, beatae esse numquam pariatur doloribus, deserunt totam natus rerum obcaecati. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, ipsum provident. Error quis facere pariatur ipsam, optio maxime commodi? Cumque dolores eaque, nobis magni nesciunt hic voluptatibus rem deleniti debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam accusamus laboriosam ipsa, ratione dicta delectus quam nisi culpa facilis cupiditate, inventore, aliquam perspiciatis facere? Quae perspiciatis veritatis eos voluptatibus? Sunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt fuga deleniti eos quisquam quis porro quaerat, at qui et! Assumenda doloribus reiciendis fugiat eos laboriosam eveniet placeat dicta blanditiis accusamus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos distinctio alias obcaecati eius provident quos nobis voluptas repellendus! Necessitatibus maiores sapiente laborum numquam cumque, eos vero totam ex rem cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias vero blanditiis doloribus natus ex, explicabo quasi excepturi tempora. Quaerat corrupti esse repudiandae iusto illo optio at voluptatibus, accusamus dolore minus.</p>
  </main>
</template>

<script setup>
import HomeNavbar from '../components/Navigation/HomeNavbar.vue';
import HomeDrawer from '../components/Navigation/HomeDrawer.vue';
</script>
